### ISSUE TITLE
Small typo

### ISSUE THREAD

**Issue by gregsadetsky** [wslack/wslack.github.io#18]
Hey,

I found a small typo in your "Comparing USDS..." article

Specifically, "legistlative " [here](https://github.com/wslack/wslack.github.io/blob/10dc01b0590052da3f548d8dd4e6d78870fb3a29/_posts/2021-02-11-pif-18f-usds.md?plain=1#L47)

Cheers!

**Comment by wslack** [comment]
TY!!!!
